//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudFlareDDNS.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudFlareDDNS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string About_Close {
            get {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap application_double {
            get {
                object obj = ResourceManager.GetObject("application_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to update 的當地語系化字串。
        /// </summary>
        internal static string Logger_Failed {
            get {
                return ResourceManager.GetString("Logger_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 minutes for domain 的當地語系化字串。
        /// </summary>
        internal static string Logger_Interval {
            get {
                return ResourceManager.GetString("Logger_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting CloudFlare DDNS updater GUI 的當地語系化字串。
        /// </summary>
        internal static string Logger_RunGUI {
            get {
                return ResourceManager.GetString("Logger_RunGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting CloudFlare DDNS updater service 的當地語系化字串。
        /// </summary>
        internal static string Logger_RunService {
            get {
                return ResourceManager.GetString("Logger_RunService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Service stopping 的當地語系化字串。
        /// </summary>
        internal static string Logger_ServiceStop {
            get {
                return ResourceManager.GetString("Logger_ServiceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Starting auto updates every 的當地語系化字串。
        /// </summary>
        internal static string Logger_Start {
            get {
                return ResourceManager.GetString("Logger_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current External IP Address: 的當地語系化字串。
        /// </summary>
        internal static string Main_ExterrnalAddress {
            get {
                return ResourceManager.GetString("Main_ExterrnalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        internal static string Main_HostsList_Header1 {
            get {
                return ResourceManager.GetString("Main_HostsList_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        internal static string Main_HostsList_Header2 {
            get {
                return ResourceManager.GetString("Main_HostsList_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Main_HostsList_Header3 {
            get {
                return ResourceManager.GetString("Main_HostsList_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Host 的當地語系化字串。
        /// </summary>
        internal static string Main_HostsList_Header4 {
            get {
                return ResourceManager.GetString("Main_HostsList_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Level 的當地語系化字串。
        /// </summary>
        internal static string Main_LogControl_Header1 {
            get {
                return ResourceManager.GetString("Main_LogControl_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message 的當地語系化字串。
        /// </summary>
        internal static string Main_LogControl_Header2 {
            get {
                return ResourceManager.GetString("Main_LogControl_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_About {
            get {
                return ResourceManager.GetString("Main_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Exit {
            get {
                return ResourceManager.GetString("Main_MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fetch Records 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Fetch {
            get {
                return ResourceManager.GetString("Main_MenuItem_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_File {
            get {
                return ResourceManager.GetString("Main_MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Help 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Help {
            get {
                return ResourceManager.GetString("Main_MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimise to tray 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Minimise {
            get {
                return ResourceManager.GetString("Main_MenuItem_Minimise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Settings {
            get {
                return ResourceManager.GetString("Main_MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tools 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Tools {
            get {
                return ResourceManager.GetString("Main_MenuItem_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Records 的當地語系化字串。
        /// </summary>
        internal static string Main_MenuItem_Update {
            get {
                return ResourceManager.GetString("Main_MenuItem_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CloudFlare DDNS Updater 的當地語系化字串。
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API Key: 的當地語系化字串。
        /// </summary>
        internal static string Settings_APIKey {
            get {
                return ResourceManager.GetString("Settings_APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply 的當地語系化字串。
        /// </summary>
        internal static string Settings_Apply {
            get {
                return ResourceManager.GetString("Settings_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Fetch Time (Minutes): 的當地語系化字串。
        /// </summary>
        internal static string Settings_AutoFetchTime {
            get {
                return ResourceManager.GetString("Settings_AutoFetchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Domain Name: 的當地語系化字串。
        /// </summary>
        internal static string Settings_Domain {
            get {
                return ResourceManager.GetString("Settings_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email Address: 的當地語系化字串。
        /// </summary>
        internal static string Settings_EmailAddress {
            get {
                return ResourceManager.GetString("Settings_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Windows Event Log: 的當地語系化字串。
        /// </summary>
        internal static string Settings_UseWindowsEventLog {
            get {
                return ResourceManager.GetString("Settings_UseWindowsEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Updates will continue in the background 的當地語系化字串。
        /// </summary>
        internal static string Tooltip_Text {
            get {
                return ResourceManager.GetString("Tooltip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
